
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/snap/clion/248/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Linux - 6.2.0-26-generic - x86_64
...
